[tool.poetry]
name = "makenew-python-app"
version = "1.0.3"
description = "Package skeleton for a python app."
authors = ["Evan Sosenko <razorx@evansosenko.com>"]
license = "MIT"
readme = "README.rst"
homepage = "https://github.com/makenew/python-app"
repository = "https://github.com/makenew/python-app"
include = ['poetry.lock']

[tool.poetry.dependencies]
python = "3.8.2"
tornado = "^6.0.4"
structlog = "^20.1.0"
pinject = "^0.14.1"

[tool.poetry.dev-dependencies]
bumpversion = "^0.5.3"
pylint = "^2.4"
pytest = "^5.2"
pytest-cov = "^2.8"
pytest-incremental = "^0.5.0"
pytest-runner = "^5.2"
pytest-watch = "^4.2"
twine = "^3.0"

[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"
